### ISSUE TITLE
about the dataset

### ISSUE THREAD

**Issue by yogixRush** [LecJackS/CS-330-Deep-Multi-Task-and-Meta-Learning#1]
Hi, in the omniglot dataset, i think there are about 1600 classes, in your code, you view '/omniglot_resized/ULOG/' as a class, however, meta-learning papers typically view '/omniglot_resized/ULOG/character16' as a whole class... and thus the label name should be something like 'ULOG_character16', can you check that?

**Comment by JC-chen97** [comment]
Hello,  I want to ask why some examples in the same class are different, and some examples of different classes are the same, as shown in block 8-9 of Homework 1 - Step by step.ipynb.

**Comment by LecJackS** [comment]
Hi @yogixRush ,

I made some fixes to the code. I followed the guidelines from CS-330 course, where labels for each class (languages) are just one hot vectors, relatives to each meta batch.

Also, you can read issue #2 where I discuss in more detail the concepts of classes, examples, and batches (for this particular project).

Let me know if you have questions after that.

**Comment by yogixRush** [comment]
> Hi @yogixRush ,
> 
> I made some fixes to the code. I followed the guidelines from CS-330 course, where labels for each class (languages) are just one hot vectors, relatives to each meta batch.
> 
> Also, you can read issue #2 where I discuss in more detail the concepts of classes, examples, and batches (for this particular project).
> 
> Let me know if you have questions after that.

thanks, i noticed that in the next homework of CS330, the standard answer of load_data.py is provided

**Comment by LecJackS** [comment]
@yogixRush Hi! I'm letting you know that what I said about taking the classes as languages and not individual characters is wrong, and you were completely right.

I found myself on this course again, and reading the [SNAIL paper](https://arxiv.org/pdf/1707.03141.pdf) opened my eyes:

> The Omniglot and mini-ImageNet datasets for few-shot image classification are the standard benchmarks in supervised meta-learning. Introduced by Lake et al. (2011), Omniglot consists of black and-white images of handwritten characters gathered from 50 languages, **for a total of 1632 different classes with 20 instances per class**.

Thanks for the hint on hw2!
